### ISSUE TITLE
Autovotekick is dead

### ISSUE THREAD

**Issue by Auditormadness9** [lnx00/Lmaobox-Lua#11]
![image](https://user-images.githubusercontent.com/71278545/211383158-2ce4aa4a-9da5-4fa3-8072-2f79611772f9.png)
it keeps spamming this in the console but the menu always says:
![image](https://user-images.githubusercontent.com/71278545/211383300-48eee520-7514-4093-9fe6-34cb3a526228.png)

**Comment by lnx00** [comment]
yea it's not read yet
