### ISSUE TITLE
Auto Queue isn't working properly

### ISSUE THREAD

**Issue by lnx00** [lnx00/Lmaobox-Lua#19]
There have been reports that Auto Queue isn't working as intended anymore.

**Comment by BGAMER69** [comment]
Please fix it asap

**Comment by lnx00** [comment]
This seems to be an issue on Lmaobox side. The Draw callback isn't being executed in the main menu, so the AutoQueue script can't run.

**Comment by BGAMER69** [comment]
> > Please fix it asap
> 
> how hard is it to click two buttons consecutively

very hard
