### ISSUE TITLE
tf2

### ISSUE THREAD

**Issue by flexi09** [lnx00/Lmaobox-LUA#5]
Hello, Are you making a script to order?
it is necessary for tf2, pumping in mann vs machine and output to the point of the character.

**Comment by lnx00** [comment]
I have the machine, tf2 has output of character. necessary it is pumping for the order?

**Comment by flexi09** [comment]
example https://mega.nz/file/99txBAqQ#8vD2geILSGqQMVr3uT68Eh8y41xxJgoctIkOye9ukX8

**Comment by flexi09** [comment]
Аnd for manhattan, can you do that?

**Comment by lnx00** [comment]
no
