### ISSUE TITLE
Where do we put these? And how do we enable them in Lbox?

### ISSUE THREAD

**Issue by Auditormadness9** [lnx00/Lmaobox-LUA#9]

**Comment by lnx00** [comment]
You need to use the Lmaobox Beta. Then you can simply place your desired Lua files into the `%localappdata%` folder.

**Comment by Auditormadness9** [comment]
> You need to use the Lmaobox Beta. Then you can simply place your desired Lua files into the `%localappdata%` folder.

got it, thanks a ton!
